# Generated by Django 6.0.5 on 2026-05-10 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the food item', max_length=200)),
                ('calories', models.PositiveIntegerField(help_text='Number of calories')),
                ('date_added', models.DateField(default=django.utils.timezone.now, help_text='Date when food was added')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added', '-created_at'],
            },
        ),
    ]
